### ISSUE TITLE
Help fixing missing files.

### ISSUE THREAD

**Issue by vDucky** [DouglasTaylorSupportGroup/EinsteinBot#3]
Import "discord" could not be resolved
Import "discord.ext" could not be resolved
Import "validators" could not be resolved
Import "cheinsteinpy" could not be resolved

I'm new when it comes to this stuff so some help would be amazing LOL. 
Also I love that you're providing this to everyone. Thank you for ur work <3

**Comment by vDucky** [comment]
Also, do you have a Discord by any chance? I feel like it would easier to communicate with you on that platform haha

**Comment by vDucky** [comment]
Okay, so I've solved the problem that issue myself ^ 
Had to do some research haha
Now the only thing im having a problem with is this:

Traceback (most recent call last):
  File "C:\Users\EinsteinBot-master\bot.py", line 21, in <module>
    bot.load_extension(f"cogs.{name}")
  File "C:\Users\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\ext\commands\bot.py", line 678, in load_extension
    self._load_from_module_spec(spec, name)
  File "C:\Users\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\ext\commands\bot.py", line 609, in _load_from_module_spec
    raise errors.ExtensionFailed(key, e) from e
discord.ext.commands.errors.ExtensionFailed: Extension 'cogs.info' raised an error: AttributeError: module 'discord' has no attribute 'ui'
PS C:\Users\EinsteinBot-master>


I keep getting this error when i run it^

**Comment by vDucky** [comment]
Alright after a long tedious day of me trying to find the solution to my question, I got it resolved however the Bug is still there so I guess i just have to wait haha

**Comment by Dineshomapathi** [comment]
Have you try install all requirement files by using 

pip install -r requirements.txt
